"""Prompt templates for agents."""

from .assessor import ASSESSOR_SYSTEM_PROMPT, QUIZ_GENERATION_PROMPT, SCORING_PROMPT
from .organizer import ORGANIZER_SYSTEM_PROMPT
from .summarizer import SUMMARIZER_SYSTEM_PROMPT, AUDIENCE_TEMPLATES

__all__ = [
    "ASSESSOR_SYSTEM_PROMPT",
    "QUIZ_GENERATION_PROMPT",
    "SCORING_PROMPT",
    "ORGANIZER_SYSTEM_PROMPT",
    "SUMMARIZER_SYSTEM_PROMPT",
    "AUDIENCE_TEMPLATES",
]
